### ISSUE TITLE
Live rerender test failing (action not updating)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/webservices-dispatch-action#47]
It looks like the update step [started failing in late January]( https://github.com/conda-forge/webservices-dispatch-action/actions/runs/7683814254/job/20939592287 )

Recently ran [a new build]( https://github.com/conda-forge/webservices-dispatch-action/actions/runs/8181357618/job/22371001813 ). Though am still seeing the same issue

```python
Traceback (most recent call last):
  File "/home/runner/work/webservices-dispatch-action/webservices-dispatch-action/tests/run_live_rerender_test.py", line 219, in <module>
checkout branch...
undoing edit to a workflow...
commiting...
push to origin...
    _run_test()
  File "/home/runner/work/webservices-dispatch-action/webservices-dispatch-action/tests/run_live_rerender_test.py", line 100, in _run_test
    assert "MNT:" in output
AssertionError
```

Do we know what is happening here?

**Comment by jakirkham** [comment]
cc @beckermr

**Comment by jakirkham** [comment]
Possible fix in PR: https://github.com/conda-forge/webservices-dispatch-action/pull/48

**Comment by jakirkham** [comment]
Looks like things are working again. Closing as completed
